[package]
name = "type-proj"
version = "0.1.0"
authors = ["YOUR NAME HERE <YOU@pitt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.2.0"
colored = "2.0.0"